### ISSUE TITLE
Library documentation?

### ISSUE THREAD

**Issue by cbajgier** [TinyCircuits/TinyCircuits-TinyScreen_Lib#3]
I've seen a couple of tutorials, and I can see the functions of the library described in the comments, but is there any formal reference documentation available for TinyScreen-Lib?

Thank you.

**Comment by TinyCircuits** [comment]
Right now there is no formal documentation on this, other than what's in the source code.  We plan on revising and updating this more, and do plan more formal docs for this.

Thanks!
