### ISSUE TITLE
Line 487 in TinyScreen.cpp error TinyScreen+

### ISSUE THREAD

**Issue by cbolgiano** [TinyCircuits/TinyCircuits-TinyScreen_Lib#7]
I am receiving an error on line 487 in TinyScreen.cpp when trying to create a CI script using travis and platformio.

Here is the ouput:
`.piolibdeps/TinyScreen/TinyScreen.cpp: In constructor 'TinyScreen::TinyScreen(uint8_t)':                                                        
.piolibdeps/TinyScreen/TinyScreen.cpp:487:12: error: 'SPI1' was not declared in this scope                                                      
TSSPI=&SPI1;                                                                                                                                    
^                                                                                                                                               
Compiling .pioenvs/tinyscreen+/lib/tinywatch-button/tinywatch-button.o                                                                          
*** [.pioenvs/tinyscreen+/lib/TinyScreen/TinyScreen.o] Error 1
`

Was assigning SPI1 to TSSPI intended?

My platformio.ini:

> [common_env_data]
> lib_deps_builtin =
>   Wire
> lib_deps_external =
>   https://github.com/TinyCircuits/TinyCircuits-TinyScreen_Lib/archive/master.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/Time-master.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/arduino-BLEPeripheral-master.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/tinywatch-time.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/tinywatch-sleep.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/tinywatch-notification.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/tinywatch-display.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/tinywatch-vibrate.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/tinywatch-button.zip
>   https://github.com/cbolgiano/tinywatch/raw/develop/libs/tinywatch-battery.zip
> 
> [env:tinyscreen+]
> platform = atmelsam
> 
> board = zero
> 
> framework = arduino
> 
> lib_deps =
>   ${common_env_data.lib_deps_builtin}
>   ${common_env_data.lib_deps_external}

**Comment by TinyCircuits** [comment]
Yes, SPI1 is correct for the TinyScreen+, we have a custom platform definition for the Arduino IDE for this, haven't tried using this on Platformio but assume that this would need to be set up there as well.

**Comment by cbolgiano** [comment]
Thank you for the information.
