### ISSUE TITLE
Tinyduino GPS Module with Tinyscreen +

### ISSUE THREAD

**Issue by LSHTM-ORK** [TinyCircuits/TinyCircuits-TinyScreen_Lib#8]
The Tinyscreen+ does not appear to work with softwareserial.h library and no documentation explains how to feed data from GPS module to the tinyscreen + via hardware serial. Please could docs be updated with code example to demonstrate.

**Comment by TinyCircuits** [comment]
Thanks for using this - check out the tutorial at this location about how to do this:
https://tinycircuits.com/blogs/learn/121671239-using-the-gps-tinyshield-tutorial
